// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7DU1ynWvFV4ffifZI5FSftPBAltvqG3g',
    appId: '1:664137526322:web:d0fb513fe2b0e82b15602b',
    messagingSenderId: '664137526322',
    projectId: 'stock-smart-6dccc',
    authDomain: 'stock-smart-6dccc.firebaseapp.com',
    storageBucket: 'stock-smart-6dccc.firebasestorage.app',
    measurementId: 'G-2JKLGGG3R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkOy8QPKKR-TrJZejBuQAhOF7fZIFE-Ko',
    appId: '1:664137526322:android:44d4f2b10d7adaaf15602b',
    messagingSenderId: '664137526322',
    projectId: 'stock-smart-6dccc',
    storageBucket: 'stock-smart-6dccc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOf76jo2lgtg8K21DtSUcKs8eDKnhDRBM',
    appId: '1:664137526322:ios:bd7c9b8f2e43dc9315602b',
    messagingSenderId: '664137526322',
    projectId: 'stock-smart-6dccc',
    storageBucket: 'stock-smart-6dccc.firebasestorage.app',
    iosBundleId: 'com.example.stockSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOf76jo2lgtg8K21DtSUcKs8eDKnhDRBM',
    appId: '1:664137526322:ios:bd7c9b8f2e43dc9315602b',
    messagingSenderId: '664137526322',
    projectId: 'stock-smart-6dccc',
    storageBucket: 'stock-smart-6dccc.firebasestorage.app',
    iosBundleId: 'com.example.stockSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7DU1ynWvFV4ffifZI5FSftPBAltvqG3g',
    appId: '1:664137526322:web:dd98c7cd18a59de415602b',
    messagingSenderId: '664137526322',
    projectId: 'stock-smart-6dccc',
    authDomain: 'stock-smart-6dccc.firebaseapp.com',
    storageBucket: 'stock-smart-6dccc.firebasestorage.app',
    measurementId: 'G-XJFSZV95QY',
  );
}
